import jsPDF from "jspdf";
import type { UIMessage } from "ai";

function textOf(m: UIMessage): string {
  return m.parts.map((p) => (p.type === "text" ? p.text : "")).join("");
}

export function chatToPlainText(title: string, messages: UIMessage[]): string {
  const header = `HalfPace TaxGPT — ${title}\nExported: ${new Date().toLocaleString()}\n\n`;
  const body = messages
    .map((m) => {
      const who = m.role === "user" ? "You" : "HalfPace TaxGPT";
      return `${who}:\n${textOf(m)}\n`;
    })
    .join("\n---\n\n");
  return header + body + "\n\nGenerated by HalfPace TaxGPT — https://halfpace.in";
}

export async function copyChat(title: string, messages: UIMessage[]) {
  const text = chatToPlainText(title, messages);
  await navigator.clipboard.writeText(text);
}

export function downloadChatText(title: string, messages: UIMessage[]) {
  const text = chatToPlainText(title, messages);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${safeName(title)}.txt`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function downloadChatPdf(title: string, messages: UIMessage[]) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setTextColor(11, 94, 215); // #0B5ED7
  doc.setFontSize(16);
  doc.text("HalfPace TaxGPT", margin, y);
  y += 20;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90, 90, 90);
  doc.setFontSize(10);
  doc.text(title, margin, y);
  y += 14;
  doc.text(`Exported: ${new Date().toLocaleString()}`, margin, y);
  y += 12;
  doc.setDrawColor(220, 220, 225);
  doc.line(margin, y, pageWidth - margin, y);
  y += 18;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  for (const m of messages) {
    const who = m.role === "user" ? "You" : "HalfPace TaxGPT";
    const body = textOf(m).trim();
    if (!body) continue;

    ensureSpace(32);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(m.role === "user" ? 20 : 11, m.role === "user" ? 20 : 94, m.role === "user" ? 30 : 215);
    doc.text(who, margin, y);
    y += 14;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 35);
    const lines = doc.splitTextToSize(body, maxWidth) as string[];
    const lineHeight = 14;
    for (const line of lines) {
      ensureSpace(lineHeight);
      doc.text(line, margin, y);
      y += lineHeight;
    }
    y += 10;
  }

  // Footer disclaimer
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 145);
    doc.text(
      "HalfPace TaxGPT can make mistakes. Verify important details with a qualified professional.",
      margin,
      pageHeight - 24,
    );
    doc.text(`Page ${i} of ${total}`, pageWidth - margin, pageHeight - 24, { align: "right" });
  }

  doc.save(`${safeName(title)}.pdf`);
}

function safeName(s: string): string {
  return (s || "halfpace-chat")
    .replace(/[^a-z0-9\-_]+/gi, "-")
    .replace(/-+/g, "-")
    .slice(0, 60);
}
